import './globals.css'

import type { Metadata } from 'next'

import { albert, glirock } from '@/app/fonts/fonts'

import Footer from '@/components/Footer'
import Navbar from '@/components/navbar/Navbar'
import WelcomeModal from '@/components/WelcomeModal'
import BreakpointIndicator from '@/components/BreakpointIndicator'

import ModalProvider from '@/providers/modal-provider'
import ToastProvider from '@/providers/toast-provider'
import { ThemeProvider } from '@/providers/theme-provider'

export const metadata: Metadata = {
  title: 'Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${albert.className} ${glirock.variable} grainy bg-blend-multiply min-h-screen antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          storageKey="theme"
        >
          <ToastProvider />
          <ModalProvider />
          {/* <WelcomeModal /> */}
          <Navbar />

          <main>{children}</main>
          <BreakpointIndicator />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
