import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ModalProvider from "@/providers/modal-provider";
import ToastProvider from "@/providers/toast-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import WelcomeModal from "@/components/WelcomeModal";
import BreakpointIndicator from "@/components/BreakpointIndicator";

const font = Inter({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className} grainy bg-blend-multiply`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          storageKey="theme"
        >
          <ToastProvider />
          <ModalProvider />
          <WelcomeModal />
          <Navbar />
          {/* <WhatsAppButton /> */}
          <BreakpointIndicator />
          <main className=" ">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
